const LogName = {
    INFO: {
        API_CALL_INFO: 'API_CALL_INFO',
        NEW_PAIRWISEDID_INFO: 'NEW_PAIRWISEDID_INFO',
        CREDENTIAL_ISSUANCE_INFO: 'CREDENTIAL_ISSUANCE_INFO',
        CREDENTIAL_VERIFICATION_INFO: 'CREDENTIAL_VERIFICATION_INFO',
        CREDENTIAL_REVOCATION_INFO: 'CREDENTIAL_REVOCATION_INFO'
    },
    ERROR: {
        LEGACY_ERROR: 'LEGACY_ERROR',
        LEDGER_ERROR: 'LEDGER_ERROR',
        INTERNAL_ERROR: 'INTERNAL_ERROR'
    }
};

export default LogName;