@host = http://localhost:4000

GET {{host}}/api/instances/health
###

GET {{host}}/api/instances/3
###

GET {{host}}/api/instances?perPage=10&page=1&sort=siteName+asc,serviceName+desc,name+asc,endpoint+desc,status+asc
###

GET {{host}}/api/instances?siteId=1
###

GET {{host}}/api/instances?serviceId=4
###

GET {{host}}/api/instances?status=false
###